### ISSUE TITLE
How to access Chinese version on the website?

### ISSUE THREAD

**Issue by H4M5TER** [Donokami/politiscales#5]
I made Chinese translation on Crowdin several days ago.
And I found that maintainer have committed it to translation branch.
But there isn't a Chinese language to select on the website.

**Comment by Donokami** [comment]
> I made Chinese translation on Crowdin several days ago.
> And I found that maintainer have committed it to translation branch.
> But there isn't a Chinese language to select on the website.

Hey! And thanks a lot for your contribution!
I saw that you did translate Politiscales interface in Chinese, but last time I checked there was no questions translation.
I'm adding the Chinese version to the website as soon as possible 😉

**Comment by Donokami** [comment]
Chinese is now available on https://politiscales.party / https://politiscales.fun / https://politiscales.fr @H4M5TER ! Thanks for your hard work, and don't hesitate to share it to your Chinese friends!

**Comment by H4M5TER** [comment]
It's glad to contribute!
Thank you for react quickly!
